<?php

$student = ["S01" => "Dung", "S12" => "Thu", "S08" => "Phuc", "S09" => "Thinh", "S10" => "Thien", "S03" => "Nhan", "S05" => "Thang", "S21" => "Tam"];

$student_2 = ["S91" => "Dung", "S192" => "Thu", "S88" => "Phuc", "S19" => "Thinh", "S10" => "Thien", "S03" => "Nhan", "S15" => "Thang", "S21" => "Tam", "S33"=>"Toan", "S34"=>"Quang"];


$modules = ["M1" => "Java 1", "M2" => "Java 2", "M3" => "PHP", "M6" => "SQL Server"];



?>